### Create restaurant
POST http://localhost:3000/api/restaurants
Content-Type: application/json

{
  "name": "Very Good Cafe",
  "location": "0,0",
  "cuisines": ["French", "Italian"] 
}

### Create restaurant review
POST http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3/reviews
Content-Type: application/json

{
  "review": "Amazing food",
  "rating": 4
}

### Get restaurant by id
GET http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3

### Get restaurant with invalid id
GET http://localhost:3000/api/restaurants/123456

### Get restaurant reviews
GET http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3/reviews