### Create restaurant
POST http://localhost:3000/api/restaurants
Content-Type: application/json

{
  "name": "Very Good Cafe",
  "location": "0,0",
  "cuisines": ["Mexican", "Italian"] 
}

### Create restaurant review
POST http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3/reviews
Content-Type: application/json

{
  "review": "Very good indeed",
  "rating": 4
}

### Get restaurant by id
GET http://localhost:3000/api/restaurants/JdOTu2SjuqUlpCMotimV-

### Get restaurant with invalid id
GET http://localhost:3000/api/restaurants/123456

### Get restaurant reviews
GET http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3/reviews

### Get paginated restaurant reviews
GET http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3/reviews?page=1&limit=2

### Delete restaurant review
DELETE http://localhost:3000/api/restaurants/-Ce17-xkk3AH2DpohPdF3/reviews/EYhh6EdLBpHfN8KsqH-kg